# Generated by Django 5.2.6 on 2025-09-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('progress', 'In Progress'), ('done', 'Done')], default='todo', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
