# Generated by Django 5.2.6 on 2025-09-30 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0002_alter_task_options_task_status_alter_task_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='is_done',
        ),
    ]
